import { useState } from "react";
import { CheckCircle2, Home, Briefcase, Navigation, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { databases, DATABASE_ID, ORDERS_COLLECTION_ID } from "@/lib/appwrite";
import { ID } from "appwrite";

export function CheckoutModal({ t, lang, user, addresses, cartItems, cartTotal, onClose, onConfirm }) {
  const [selectedLocation, setSelectedLocation] = useState(addresses && addresses.length > 0 ? addresses[0].details : "");
    const [newLocation, setNewLocation] = useState("");
      const [isNew, setIsNew] = useState(false);
        const [isSubmitting, setIsSubmitting] = useState(false);

          const handleConfirm = async () => {
              const location = isNew ? newLocation.trim() : selectedLocation;
                  if (!location) return;

                      setIsSubmitting(true);

                          try {
                                const orderPayload = {
                                        customer_name: user?.name || "Customer",
                                                customer_phone: user?.phone || "0000000000",
                                                        items: JSON.stringify(cartItems),
                                                                location: location,
                                                                        status: "pending",
                                                                                total: Math.round(Number(cartTotal) || 0),
                                                                                      };

                                                                                            await databases.createDocument(
                                                                                                    DATABASE_ID,
                                                                                                            ORDERS_COLLECTION_ID,
                                                                                                                    ID.unique(),
                                                                                                                            orderPayload
                                                                                                                                  );

                                                                                                                                        onConfirm(location);
                                                                                                                                              onClose();
                                                                                                                                                  } catch (error: any) {
                                                                                                                                                        console.error("Appwrite order insert error:", error);
                                                                                                                                                              alert(`حدث خطأ أثناء إرسال الطلب: ${error.message || "خطأ غير معروف"}`);
                                                                                                                                                                  } finally {
                                                                                                                                                                        setIsSubmitting(false);
                                                                                                                                                                            }
                                                                                                                                                                              };

                                                                                                                                                                                const isDisabled = (!isNew && !selectedLocation) || (isNew && !newLocation.trim());

                                                                                                                                                                                  return (
                                                                                                                                                                                      <div className="absolute inset-0 z-[60] flex items-end justify-center bg-black/60 backdrop-blur-sm animate-in fade-in">
                                                                                                                                                                                            <Card className="flex max-h-[85vh] w-full flex-col rounded-t-3xl border-yellow-300/20 bg-slate-900 text-white shadow-2xl">
                                                                                                                                                                                                    <CardHeader className="flex flex-row items-center justify-between p-4">
                                                                                                                                                                                                              <CardTitle className="text-lg font-bold text-slate-800 dark:text-white">{t.checkout}</CardTitle>
                                                                                                                                                                                                                        <Button variant="ghost" size="icon" onClick={onClose} className="rounded-full text-slate-400 hover:text-white">
                                                                                                                                                                                                                                    <X className="h-5 w-5" />
                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                              <CardContent className="overflow-y-auto space-y-4 p-4">
                                                                                                                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                                                                                                                    <label className="text-sm font-medium text-slate-300">{t.selectAddress}</label>
                                                                                                                                                                                                                                                                                                {addresses?.map((addr: any) => (
                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                              key={addr.id}
                                                                                                                                                                                                                                                                                                                                              onClick={() => { setIsNew(false); setSelectedLocation(addr.details); }}
                                                                                                                                                                                                                                                                                                                                                              className={cn(
                                                                                                                                                                                                                                                                                                                                                                                "flex items-center gap-3 rounded-xl border p-3 cursor-pointer transition-all",
                                                                                                                                                                                                                                                                                                                                                                                                  !isNew && selectedLocation === addr.details
                                                                                                                                                                                                                                                                                                                                                                                                                      ? "border-yellow-500 bg-yellow-500/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                          : "border-slate-800 bg-slate-800/50 text-slate-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Home className="h-5 w-5 text-yellow-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex-1 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-medium text-white">{addr.label}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-slate-400">{addr.details}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setIsNew(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={cn(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "flex items-center gap-3 rounded-xl border p-3 cursor-pointer transition-all",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              isNew
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "border-yellow-500 bg-yellow-500/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "border-slate-800 bg-slate-800/50 text-slate-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Navigation className="h-5 w-5 text-yellow-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-sm font-medium text-white">{t.addNewAddress || "عنوان جديد"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isNew && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder={t.enterNewAddress || "اكتب العنوان بالتفصيل..."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={newLocation}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setNewLocation(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="mt-2 bg-slate-800 border-slate-700 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardFooter className="p-4 border-t border-slate-800 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-slate-400">{t.total}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-lg font-bold text-yellow-500">{cartTotal} ج.م</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleConfirm}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={isDisabled || isSubmitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-full bg-yellow-400 px-6 py-2 text-sm font-bold text-slate-900 hover:bg-yellow-500 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Send className="mx-1 h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isSubmitting ? "جاري الإرسال..." : t.sendOrder}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CardFooter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            