import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_DATABASE_ID, COMPLAINTS_TABLE_ID } from "../lib/appwrite";

export function ComplaintsPage({ t, user }: any) {
  const [submitted, setSubmitted] = useState(false);
    const [submitting, setSubmitting] = useState(false);
      const [subject, setSubject] = useState("");
        const [details, setDetails] = useState("");

          const handleSubmit = async (e: React.FormEvent) => {
              e.preventDefault();
                  setSubmitting(true);

                      const payload = JSON.stringify({
                            documentId: 'unique()',
                                  data: {
                                          customer_name: user?.name || "عميل",
                                                  customer_phone: user?.phone || "00000000",
                                                          subject: subject,
                                                                  details: details,
                                                                          status: "جديد"
                                                                                }
                                                                                    });

                                                                                        try {
                                                                                              const res = await fetch(`${APPWRITE_ENDPOINT}/databases/${APPWRITE_DATABASE_ID}/collections/${COMPLAINTS_TABLE_ID}/documents`, {
                                                                                                      method: "POST",
                                                                                                              headers: {
                                                                                                                        'X-Appwrite-Project': APPWRITE_PROJECT_ID,
                                                                                                                                  'Content-Type': 'application/json'
                                                                                                                                          },
                                                                                                                                                  body: payload,
                                                                                                                                                        });

                                                                                                                                                              const responseData = await res.json().catch(() => ({}));

                                                                                                                                                                    if (res.ok) {
                                                                                                                                                                            alert("تم إرسال الشكوى بنجاح!");
                                                                                                                                                                                    setSubmitted(true);
                                                                                                                                                                                            setSubject("");
                                                                                                                                                                                                    setDetails("");
                                                                                                                                                                                                            setTimeout(() => setSubmitted(false), 4000);
                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                          console.error("Appwrite complaint insert error:", responseData);
                                                                                                                                                                                                                                  alert("خطأ في الإرسال: " + JSON.stringify(responseData));
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                  console.error("Network error submitting complaint:", error);
                                                                                                                                                                                                                                                        alert("Network Error: " + JSON.stringify(error));
                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                  setSubmitting(false);
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                              <div className="flex flex-col gap-4 p-4 pt-12">
                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold text-slate-800 dark:text-white">{t.complaint}</h1>
                                                                                                                                                                                                                                                                                          {submitted ? (
                                                                                                                                                                                                                                                                                                  <Card className="border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950/20">
                                                                                                                                                                                                                                                                                                            <CardContent className="flex flex-col items-center gap-2 p-6 text-center">
                                                                                                                                                                                                                                                                                                                        <CheckCircle2 className="h-12 w-12 text-green-500" />
                                                                                                                                                                                                                                                                                                                                    <p className="font-semibold text-green-700 dark:text-green-400">{t.complaintSentSuccess}</p>
                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                    <Card className="border-yellow-100 shadow-sm dark:border-slate-700 dark:bg-slate-800">
                                                                                                                                                                                                                                                                                                                                                                              <CardContent className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-col gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">{t.subjectLabel}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Input value={subject} onChange={(e) => setSubject(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">{t.detailsLabel}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Textarea value={details} onChange={(e) => setDetails(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button type="submit" disabled={submitting} className="rounded-full bg-yellow-400 hover:bg-yellow-500 text-slate-900 font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {submitting ? t.submitting : t.submitComplaint}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        